# Generated by Django 4.0.5 on 2022-08-25 11:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почта/Логин')),
                ('number', models.CharField(max_length=11, verbose_name='Номер телефона')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Статус менеджера')),
                ('data_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ('data_joined',),
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='Номер счета')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата открытия')),
                ('balance', models.FloatField(default=0, verbose_name='Остаток')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Владелец', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Счет',
                'verbose_name_plural': 'Счета',
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата транзакции')),
                ('status', models.CharField(choices=[('Обрабатывается', 'Processing'), ('Успешно', 'Ok'), ('Неверно', 'Bad'), ('Ожидание превышено', 'Late'), ('Отклонено', 'Rejected')], default='Обрабатывается', max_length=18, verbose_name='Статус')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Сумма перевода')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receiv_transactions', to='core.bankaccount')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='send_transactions', to='core.bankaccount')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакций',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16, unique=True, verbose_name='Номер карты')),
                ('cvv_code', models.CharField(max_length=3, verbose_name='CVV2')),
                ('expiration_date', models.DateField(default=datetime.datetime(2025, 8, 24, 17, 2, 13, 382802), verbose_name='Дата эксплуатации')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=1000, verbose_name='Остаток')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='core.bankaccount')),
            ],
            options={
                'verbose_name': 'Карта',
                'verbose_name_plural': 'Карты',
            },
        ),
    ]
