# Generated by Django 4.0.5 on 2022-08-25 11:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2025, 8, 24, 17, 2, 16, 365525), verbose_name='Дата эксплуатации'),
        ),
    ]
